### ISSUE TITLE
Hacktoberfest2022

### ISSUE THREAD

**Issue by Vanshika61** [PiyushYadav007/Portfolio#23]
Hey @PiyushYadav007 I want to contribute in it.
Please assign me.

**Comment by PiyushYadav007** [comment]
you have to just pull request

**Comment by Vanshika61** [comment]
![image](https://user-images.githubusercontent.com/97943080/196480688-21b4fb5d-011a-450d-a74a-62ee778a7a69.png)

hey @PiyushYadav007 in your repository the uploads are disabled

**Comment by Vanshika61** [comment]
I have forked already

**Comment by PiyushYadav007** [comment]
then go to your repo which is https://github.com/Vanshika61/Portfolio then upload files over there and after that create pull request

**Comment by Vanshika61** [comment]
hey @PiyushYadav007 I have created the pr kindly merge it
